development: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hawkins
  database: kitchen_dev
  password:

test:
  <<: *default
  database: kitchen_test

production:
  <<: *default
  database: kitchen_prod
